### PR TITLE
feat: add put / get methods

### LINKED ISSUE #49: Add supported for Put/Get operations (IPNS in browsers etc)
We should add support for asking other nodes to do Put/Get operations for us (e.g. for IPNS records). This should basically be just adding support for an HTTP API call. 

cc @lidel https://github.com/ipfs/js-ipfs/issues/3722 https://github.com/ipfs/js-ipfs/issues/2921

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds `put` and `get` methods that wrap the client's `dht` methods. 

I noticed that it errors out if I pass in `Uint8Array`s to `dht.put` and `dht.get`, so this will convert to string and complain if it's not given a valid UTF-8 key. Alternatively, we could just only accept strings, but this way we support the same argument types as `dht.put` and `dht.get`, so we can front them both with one interface.

As for which interface, we could either [expand the `ContentRouting` interface](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interfaces/src/content-routing/types.d.ts) to include `put` and `get`, or define a new one and just have the `DelegatedContentRouter` implement both. Defining a new one seems a bit cleaner... maybe `ContentStorage`? 

@vasco-santos you seem like you'd have some thoughts on the interface question.

closes #49

### CODE REVIEW

**Comment by vasco-santos** [comment]
Hey @yusefnapora thanks for the PR ❤️ 

I have been thinking about namings given it feels strange to have them part of "Content Routing", when Content Routing is a "ContentRouting is a value provider layer of indirection. It is used to find information about who has what content.".

Looking into go libp2p interface definitions, I think we should probably follow them here https://github.com/libp2p/go-libp2p-core/blob/master/routing/routing.go#L49-L68 . No strong opinion on naming, but for consistency probably `ValueStoreInterface`. What do you think?

Also for broader context here, when we did a DHT refactor a couple of years ago, we also created a distinction between content routing and put(get ops with `content-fetching` naming per: https://github.com/libp2p/js-libp2p-kad-dht/tree/master/src/content-fetching . Should we move everything into value-store?

**Comment by yusefnapora** [comment]
I like `ValueStoreInterface` 👍 

Do you think that we should have a separate `DelegatedValueStore` class? Perhaps we could still put it in this repo... 

Then we can update js-libp2p's content-routing module to have both `routers` and `valueStores`, and if you enable the DHT it will just get added to both lists.

**Comment by lidel** [comment]
@yusefnapora will you have bandwitdth to continue this during this week's tribute?

**Comment by BigLep** [comment]
Moving this to draft until we're able to give a concerted effort on IPNS improvements as part of ipfs/js-ipfs#2921

**Comment by achingbrain** [comment]
Fixed in #68

**Pull request closed without merging**
