### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by alanshaw**
Needed for next js-ipfs release. Had to port some changes from https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/7

Depends on:

* [x] https://github.com/ipfs/js-ipfs-http-client/pull/1039

cc @achingbrain

### CODE REVIEW

**Comment by alanshaw** [comment]
@jacobheun I could use some help here.

The tests are now failing because `findProvs` in `ipfs-http-client` now only returns values for messages where the `Type` is 4 ([Provider](https://github.com/libp2p/go-libp2p-core/blob/6e566d10f4a5447317a66d64c7459954b969bdab/routing/query.go#L20)).

Previously it was returning values for all messages with a `Responses` array because `ipfs-api` did not do any filtering on the `Type`.

What is the right thing to do here? Do we need a streaming `findProvs` so you can get hold of this extra info?

**Comment by jacobheun** [comment]
@alanshaw fyi, i pushed up a lint fix.

Taking a look at the tests

**Comment by jacobheun** [comment]
> What is the right thing to do here? Do we need a streaming findProvs so you can get hold of this extra info?

We only care about actual providers, I don't think we need to care about the extra information. It looks like the tests will need to be updated

**Comment by achingbrain** [comment]
I'll update #7 once the dust settles on this.

**Comment by jacobheun** [comment]
The provide/findProv calls are really inconsistent, looking into it more.

**Comment by jacobheun** [comment]
@alanshaw this should be fixed with https://github.com/ipfs/js-ipfs-http-client/pull/1041. The test failures on CI are due to ipfsd-ctl resolving the current version of the http client instead of the fixed branch. Patching that locally makes the tests here pass every time.

**Comment by alanshaw** [comment]
@jacobheun it still fails 🙀

**Comment by jacobheun** [comment]
@alanshaw clearing the node_modules cache on CI and rerunning to see if it's just an issue with the transitive deps cacheing.

**Pull request merged**
